spring:
  application:
    name: "task always"

  datasource:
    driver-class-name: org.h2.Driver
    username: "sa"
    password: ""
    url: "jdbc:h2:file:~/workspace/study/task-always/db;AUTO_SERVER=TRUE"
